In [2]:
from random import choice
from numpy import array, dot, random

unit_step = lambda x: 0 if x < 0 else 1

training_data = [
    (array([0,0,1]), 0), 
    (array([0,1,1]), 1), 
    (array([1,0,1]), 1), 
    (array([1,1,1]), 1), 
] 

w = random.rand(3) 
errors = [] 
eta = 0.2 
n = 100 

for i in range(n): 
    x, expected = choice(training_data) 
    result = dot(w, x) 
    error = expected - unit_step(result) 
    errors.append(error) 
    w += eta * error * x 
    
for x, _ in training_data:
    result = dot(x, w) 
    print("{}: {} -> {}".format(x[:2], result, unit_step(result)))

[0 0]: -0.1618974184292284 -> 0
[0 1]: 0.14360492966262522 -> 1
[1 0]: 0.6304542870452627 -> 1
[1 1]: 0.9359566351371164 -> 1
